### ISSUE TITLE
Listado de Necesidades del Backend

### ISSUE THREAD

**Issue by Eghinner** [Azordev/did-admin-panel#186]
## Description
The list of requirements for front-end development
## List

- [x] A list of products in agreement with a specific 'Proveedor' is required.
- [ ] A list of attendees is required according to a specific 'Evento'.
- [x] A list of member type users for the 'Socios' table
